server:
    port: 8072
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eurekaserver:8070/eureka/
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /organization/$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#Enable all Spring Boot Actuator endpoints.
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
        exclude: env,beans
