server:
  port: 8071
spring:
  application:
    name: config-server
  profiles:
    active:
      - native
#      - vault
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AbdulrahmanQerawani/hr-config.git
        vault:
          kv-Version: 2
          port: 8200
          host: 127.0.0.1
          token: 'hvs.DkQlLevgSZwgbmPiGwdPbrJt'
encrypt:
  key: iJzP4VLhuLfT4iEr9Ay8GPV@@ku!i

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
    enabled-by-default: true



